version: "3.9"

services:
    jupyter:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8888:8888"
        volumes:
            - ./notebooks:/home/jovyan/
        environment:
            JUPYTER_ENABLE_LAB: "yes"
        command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --ip='*'"
